# 文档检查规范规则配置
rules:
  # 文本内容规范
  text_rules:
    - "文档标题必须使用规范的层级结构（H1、H2、H3等）"
    - "代码示例必须包含完整的注释和说明"
    - "每个章节必须有明确的标题"
    - "技术术语必须保持一致性"
    - "重要概念首次出现时应有详细解释"
    - "列表项目必须使用统一的格式"
    - "链接必须有效且描述清晰"
    - "表格必须有表头和清晰的列标题"
    
  # 图像内容规范
  image_rules:
    - "所有图表必须有清晰的标题和编号"
    - "流程图中的每个步骤都应有明确标注"
    - "架构图必须包含组件说明和连接关系"
    - "截图必须清晰可读，关键信息可识别"
    - "数据图表必须包含坐标轴标签和图例"
    - "图片必须有相关的文字说明或说明文字"
    - "技术示意图必须标注关键组件和流程"
    - "界面截图必须突出显示重要功能区域"
    
  # 结构规范
  structure_rules:
    - "文档必须包含目录结构"
    - "章节编号必须连续且规范"
    - "子章节层级不应超过4级"
    - "每个主要章节应有概述或引言"
    - "文档结尾应有总结或结论"
    
  # 格式规范
  format_rules:
    - "代码块必须指定编程语言"
    - "引用内容必须标明出处"
    - "专业名词必须使用正确的大小写"
    - "数字和单位之间必须有空格"
    - "中英文混排时必须有适当的空格"

# 检查严重程度配置
severity_levels:
  critical:
    - "文档标题必须使用规范的层级结构"
    - "所有图表必须有清晰的标题和编号"
    - "代码示例必须包含完整的注释和说明"
  
  warning:
    - "图片必须有相关的文字说明或说明文字"
    - "技术术语必须保持一致性"
    - "数字和单位之间必须有空格"
  
  info:
    - "中英文混排时必须有适当的空格"
    - "专业名词必须使用正确的大小写"

# 检查配置
check_config:
  # 是否检查图像内容
  check_images: true
  
  # 是否检查代码块
  check_code_blocks: true
  
  # 是否检查链接有效性
  check_links: false
  
  # 最大章节层级
  max_section_level: 4
  
  # 最小章节内容长度（字符数）
  min_section_length: 100
